const CONSTANTS = {
  ACTIONS: {
    MESSAGES_LOAD_SUCCESS: ' MESSAGES_LOAD_SUCCESS',
    MESSAGES_LOAD_ERROR: 'MESSAGES_LOAD_ERROR',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
  },
};

export default CONSTANTS;
